WITH XTAB AS
     (SELECT   H.HACKER_ID,
               S.CHALLENGE_ID,
               MAX (S.SCORE) AS MAX_SCORE
          FROM HACKERS H,
               SUBMISSIONS S
         WHERE H.HACKER_ID = S.HACKER_ID
      GROUP BY H.HACKER_ID,
               S.CHALLENGE_ID)
SELECT   XTAB.HACKER_ID,
         HACKERS.NAME,
         SUM (MAX_SCORE) AS TOTAL_SCORE
    FROM XTAB,
         HACKERS
   WHERE HACKERS.HACKER_ID = XTAB.HACKER_ID
GROUP BY XTAB.HACKER_ID,
         HACKERS.NAME
  HAVING SUM (MAX_SCORE) != 0
ORDER BY 3 DESC,
         HACKER_ID;