WITH XTAB AS
     (
       SELECT CONTEST_ID,
              HACKER_ID,
              NAME,
              (SELECT SUM (TOTAL_SUBMISSIONS)
                 FROM COLLEGES,
                      CHALLENGES,
                      SUBMISSION_STATS
                WHERE CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
                  AND COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
                  AND CHALLENGES.CHALLENGE_ID = SUBMISSION_STATS.CHALLENGE_ID) AS TOTAL_SUBMISSIONS,
              (SELECT SUM (TOTAL_ACCEPTED_SUBMISSIONS)
                 FROM COLLEGES,
                      CHALLENGES,
                      SUBMISSION_STATS
                WHERE CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
                  AND COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
                  AND CHALLENGES.CHALLENGE_ID = SUBMISSION_STATS.CHALLENGE_ID) AS TOTAL_ACCEPTED_SUBMISSIONS,
              (SELECT SUM (TOTAL_VIEWS)
                 FROM COLLEGES,
                      CHALLENGES,
                      VIEW_STATS
                WHERE CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
                  AND COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
                  AND CHALLENGES.CHALLENGE_ID = VIEW_STATS.CHALLENGE_ID) AS TOTAL_VIEWS,
              (SELECT SUM (TOTAL_UNIQUE_VIEWS)
                 FROM COLLEGES,
                      CHALLENGES,
                      VIEW_STATS
                WHERE CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
                  AND COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
                  AND CHALLENGES.CHALLENGE_ID = VIEW_STATS.CHALLENGE_ID) AS TOTAL_UNIQUE_VIEWS
         FROM CONTESTS)
SELECT   *
    FROM XTAB
   WHERE 1 = 1
     AND NOT (    TOTAL_SUBMISSIONS = 0
              AND TOTAL_ACCEPTED_SUBMISSIONS = 0
              AND TOTAL_VIEWS = 0
              AND TOTAL_UNIQUE_VIEWS = 0)
ORDER BY CONTEST_ID;
