WITH XTAB AS
     (SELECT   MIN (WANDS.COINS_NEEDED) COINS_NEEDED,
               WANDS.POWER,
               WANDS_PROPERTY.AGE
          FROM WANDS,
               WANDS_PROPERTY
         WHERE WANDS.CODE = WANDS_PROPERTY.CODE
           AND WANDS_PROPERTY.IS_EVIL = 0
      GROUP BY WANDS.POWER,
               WANDS_PROPERTY.AGE)
SELECT   WANDS.ID,
         WANDS_PROPERTY.AGE,
         WANDS.COINS_NEEDED,
         WANDS.POWER
    FROM WANDS,
         WANDS_PROPERTY,
         XTAB
   WHERE WANDS.CODE = WANDS_PROPERTY.CODE
     AND WANDS_PROPERTY.IS_EVIL = 0
     AND XTAB.COINS_NEEDED = WANDS.COINS_NEEDED
     AND XTAB.POWER = WANDS.POWER
     AND XTAB.AGE = WANDS_PROPERTY.AGE
ORDER BY WANDS.POWER DESC,
         WANDS_PROPERTY.AGE DESC;